services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun-IRC-shielded
    restart: unless-stopped
    networks:
      gluetun-IRC-network:
        ipv4_address: 172.21.0.20
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "${IRC_AIRVPN_PORT}:${IRC_AIRVPN_PORT}"
    volumes:
      - ./gluetun:/gluetun
    environment:
      - HOSTNAME=gluetun-IRC-shielded
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - FIREWALL_VPN_INPUT_PORTS=${IRC_AIRVPN_PORT}
  nginx:
    image: nginx:alpine
    container_name: nginx-IRC-shielded
    network_mode: "service:gluetun"
    restart: unless-stopped
    environment:
      - HOSTNAME=nginx-IRC-shielded
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    security_opt:
      - "label=disable"
    depends_on:
      - drop
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    network_mode: "service:gluetun"
    environment:
      - HOSTNAME=thelounge-IRC-shielded
    ports:
      - "9000:9000"
    volumes:
      - ./thelounge:/var/opt/thelounge
    restart: always

networks:
  gluetun-IRC-network:
    driver: bridge
    name: gluetun-IRC-network
    ipam:
      config:
        - subnet: 172.21.0.0/16